apiVersion: opentelemetry.io/v1beta1
kind: Instrumentation
metadata:
  name: ecommerce-instrumentation
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "spring-cloud-project.labels" . | nindent 4 }}
spec:
  envConfig:
    exporter:
      endpoint: {{ .Values.global.otel.endpoint }}
      protocol: grpc
    propagators:
      - tracecontext
      - baggage
      - b3multi
    sampler:
      type: parentbased_traceidratio
      argument: "1.0"
  resource:
    attributes:
      deployment.environment: {{ .Values.global.profile | default "prod" }}
      service.namespace: {{ .Values.global.namespace }}
  java:
    image: ghcr.io/signalfx/splunk-otel-java/splunk-otel-java:v2.30.0
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: {{ .Values.global.otel.endpoint }}
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: {{ .Values.global.otel.protocol }}
      - name: OTEL_PROPAGATORS
        value: {{ .Values.global.otel.propagators | default "w3c,tracecontext,b3multi" }}
      - name: OTEL_METRICS_EXPORTER
        value: {{ .Values.global.otel.metricsExporter | default "otlp" }}
      - name: OTEL_LOGS_EXPORTER
        value: {{ .Values.global.otel.logsExporter | default "otlp" }}
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: 'deployment.environment={{ .Values.global.profile | default "prod" }},service.namespace={{ .Values.global.namespace }}'
      - name: SPLUNK_PROFILER_ENABLED
        value: "true"
      - name: SPLUNK_PROFILER_MEMORY_ENABLED
        value: "true"
      - name: OTEL_JAVAAGENT_CONFIG
        value: "otel.javaagent.extensions=splunk-otel-profiler"