apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-otel-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "spring-cloud-project.labels" . | nindent 4 }}
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    
    processors:
      batch:
      memory_limiter:
        limit_mib: 400
        spike_limit_size_mib: 100
      attributes:
        - key: service.name
          value: "{{`{{`}}service.name{{`}}`}}"
          action: upsert
        - key: deployment.environment
          value: "{{`{{`}}deployment.environment{{`}}`}}"
          action: insert
    
    exporters:
      splunk:
        endpoint: {{`{{`}}SPLUNK_INGEST_URL{{`}}`}}
        token: {{`{{`}}SPLUNK_ACCESS_TOKEN{{`}}`}}
        timeout: 10s
        tls:
          insecure: false
      logging:
        loglevel: debug
    
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, memory_limiter]
          exporters: [splunk, logging]
        metrics:
          receivers: [otlp]
          processors: [batch, memory_limiter]
          exporters: [splunk, logging]
        logs:
          receivers: [otlp]
          processors: [batch, memory_limiter]
          exporters: [splunk, logging]