apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "spring-cloud-project.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.global.postgres.username | default "postgres" }}
  POSTGRES_PASSWORD: {{ .Values.global.postgres.password | default "postgres" }}
  RABBITMQ_USER: {{ .Values.global.rabbitmq.username | default "guest" }}
  RABBITMQ_PASSWORD: {{ .Values.global.rabbitmq.password | default "guest" }}
  MAIL_USERNAME: {{ .Values.global.mail.username | default "" }}
  MAIL_PASSWORD: {{ .Values.global.mail.password | default "" }}
  SPLUNK_ACCESS_TOKEN: {{ .Values.global.splunk.accessToken | default "" }}
  SPLUNK_INGEST_URL: {{ .Values.global.splunk.ingestUrl | default "" }}
  SPLUNK_REALM: {{ .Values.global.splunk.realm | default "sg0" }}
