spring:
  config:
    import: optional:configserver:http://config-server:8888
---
spring:
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 5s
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 3
        max-concurrency: 10
        prefetch: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,circuitbreakers,ratelimiters
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    reactor.netty: INFO