spring:
  application:
    name: payment-service
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  config:
    import: optional:configserver:http://config-server:8888