server:
  port: 8081

spring:
  application:
    name: product
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: product_db
      auto-index-creation: true
  cloud:
    config:
      import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://mongodb:27017
      database: product_db
      auto-index-creation: true

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE:product_db}
      auto-index-creation: true
