apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-cloud-config
  namespace: ecommerce
data:
  SPRING_PROFILES_ACTIVE: "docker"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_PROPAGATORS: "w3c,tracecontext"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_LOGS_EXPORTER: "otlp"
