apiVersion: v1
kind: Secret
metadata:
  name: spring-cloud-secrets
  namespace: ecommerce
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  SPLUNK_ACCESS_TOKEN: ""
  SPLUNK_INGEST_URL: ""
  SPLUNK_REALM: "sg0"