apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: ecommerce-dev

namePrefix: dev-

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: config-server
      spec:
        replicas: 1
        template:
          spec:
            containers:
              - name: config-server
                resources:
                  limits:
                    memory: "256Mi"
                    cpu: "250m"
                  requests:
                    memory: "128Mi"
                    cpu: "100m"
    target:
      kind: Deployment
      labelSelector: app=config-server
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: gateway
      spec:
        replicas: 1
    target:
      kind: Deployment
      labelSelector: app=gateway

configMapGenerator:
  - name: spring-cloud-config
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=dev

images:
  - name: config-server
    newTag: dev
  - name: eureka-server
    newTag: dev
  - name: auth-server
    newTag: dev
  - name: gateway
    newTag: dev
  - name: product
    newTag: dev
  - name: category
    newTag: dev
  - name: order-service
    newTag: dev
  - name: inventory-service
    newTag: dev
  - name: payment-service
    newTag: dev
  - name: notification-service
    newTag: dev
